site_name: HPMPC Documentation
repo_url: https://github.com/chart21/hpmpc
site_url: https://c.harth-kitzerow.de/mkdocs-hpmpc/
theme:
  name: material
  features:
  # - navigation.instant
  - navigation.instant.preview
  # - navigation.tabs
  # - navigation.tabs.sticky
  # - navigation.sections
  - navigation.expand
  - navigation.path
  - navigation.top
  # - toc.integrate
  - toc.follow
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: en
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch light/dark mode to system preference

plugins:
  - social
  - search

nav:
  - Home: 'index.md'
  - 'Software Components':
    - 'Core': 'core.md'
    - 'Protocols': 'protocols.md'
    - 'Datatypes': 'datatypes.md'
    - 'Programs': 'programs.md'
    - 'Measurements': 'measurements.md'
    - "Neural Networks": "nn.md"
  - "Configurations": "configurations.md"
  - "The Vectorized Programming Model": "parallel-model.md"
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/chart21/hpmpc

markdown_extensions:
  - material.extensions.preview:
  - toc:
      permalink: false
      title: On this page

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2024 <a href="https://github.com/chart21"  target="_blank" rel="noopener">Christopher Harth-Kitzerow</a>
